sudo: false
language: node_js
node_js: 6
addons:
  apt:
    packages:
      - wine
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm run test
after_script:
  - npm run package
